### ISSUE TITLE
求教，php代码是放到哪个文件里面？

### ISSUE THREAD

**Issue by renqiang06** [YanlongMa/TypechoPlugins#1]
1.需要更改步骤3的php代码里面的路径么，默认typecho的sidebar.php路径是usr/theme/default/sidebar.php？
2.我将步骤3的php代码放在了根目录的index.php里面，对么？
谢谢

**Comment by yanlongma** [comment]
1. 不需要
2. 根据自己需要来，如果每个页面都要展示，最好放在公共模板中，比如 sidebar.php

**Comment by renqiang06** [comment]
@YanlongMa 你好，我这小白还是有点问题
我把代码放在typecho根目录的index.php最后：
`/** 注册一个结束插件 */
Typecho_Plugin::factory('index.php')->end();
Typecho_Plugin::factory('usr/themes/sidebar.php')->tagCloud();`
测试发现，标签显示在了网页底部，是需要theme/default/sidebar.php文件中还有啥设置么？

**Comment by yanlongma** [comment]
如果主题和默认的不一样，需要重写插件的render方法。
